version: '3.8'
services:
  exit:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: hive-namenode
    hostname: hive-namenode
    volumes:
      - hive_namenode:/hadoop/dfs/name
    ports:
      - "9870:9870"      # HDFS NameNode web UI
    environment:
      - CLUSTER_NAME=demo
      - CORE_CONF_fs_defaultFS=hdfs://hive-namenode:8020
      - DFS_NAMENODE_HTTP_ADDRESS=hive-namenode:9870
    networks:
      - hadoop

  hive-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: hive-datanode
    hostname: hive-datanode
    volumes:
      - hive_datanode:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hive-namenode:8020
    ports:
      - "9864:9864"      # HDFS DataNode web UI
    networks:
      - hadoop
    depends_on:
      - hive-namenode

  hive-metastore:
    image: bde2020/hive-metastore-postgresql
    container_name: hive-metastore
    hostname: hive-metastore
    ports:
      - "9083:9083"      # Hive Metastore port
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hive-namenode:8020
    networks:
      - hadoop
    depends_on:
      - hive-namenode
      - hive-datanode

  hive-server:
    image: bde2020/hive
    container_name: hive-server
    hostname: hive-server
    ports:
      - "10000:10000"      # HiveServer2 Thrift port
    environment:
      - SERVICE=hiveserver2
      - HIVE_CONF_HIVE_SERVER2_THRIFT_BIND_HOST=hive-server
      - HIVE_CONF_HIVE_SERVER2_THRIFT_PORT=10000
      - HIVE_METASTORE_HOST=hive-metastore
      - CORE_CONF_fs_defaultFS=hdfs://hive-namenode:8020
    networks:
      - hadoop
    depends_on:
      - hive-metastore

networks:
  hadoop:
    driver: bridge

volumes:
  hive_namenode:
  hive_datanode:
