version: '3.8'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    hostname: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    ports:
      - "9870:9870"      # HDFS NameNode web UI
    environment:
      - CLUSTER_NAME=demo
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - DFS_NAMENODE_HTTP_ADDRESS=namenode:9870
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    hostname: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9864:9864"      # HDFS DataNode web UI
    networks:
      - hadoop
    depends_on:
      - namenode

  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"      # Spark master web UI
      - "7077:7077"      # Spark master port
    environment:
      - ENABLE_INIT_DAEMON=false
      - SPARK_MASTER_HOST=spark-master
      - PATH=/spark/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    networks:
      - hadoop
    depends_on:
      - namenode
      - datanode

  spark-worker:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"      # Spark worker web UI
    environment:
      - ENABLE_INIT_DAEMON=false
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - hadoop

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  hadoop:
    driver: bridge
